name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        name: Clone the repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        name: Install Node.JS
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{env.STORE_PATH}}
          key: ${{runner.os}}-pnpm-cache-${{ hashFiles('./pnpm-lock.yaml')}}
          restore-keys: ${{runner.os}}-pnpm-cache-
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Build website
        shell: bash
        run: pnpm build
      - name: Upload build artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: build
          path: ./build/
          include-hidden-files: true
  deploy:
    name: Deploy to the server
    runs-on: ubuntu-latest
    needs: build
    if: ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master')
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build
          path: ./build/
      - name: Submit built files to the FTP server
        uses: SamKirkland/FTP-Deploy-Action@a51268f67f6605236975928ae28b0f7e9971d50a # v4.3.6
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./build/
          server-dir: /




